config/routes.rb
Vsr::Application.routes.draw do
  devise_for :user, :path=>'user', :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
  end

  match "editor_sample" => "projects#editor_sample"
  match "presentation/:id" => "projects#preview", :as => :presentation

  resources :admin_rights, only: [:destroy]
  resources :user_activations, :only => [:edit,:update, :index, :create, :destroy]  
  resources :contacts, :only => [:create, :destroy, :index, :update]
  resources :view_items do
    resources :view_items, :only=>[:create,:update,:destroy, :show]
  end
  resources :invitations

  resources :contact_groups do
    resources :contacts, :only => [:create, :update, :destroy, :show, :index]
  end

  resources :projects do
    resources :viewers, :only=>[:create,:destroy,:index] do
      resources :invitations
    end

    resources :user_actions, :only=>[:create,:index,:update]

    collection do
      get :dashboard
    end

    member do
      get 'edit_presentation'
      get 'preview'
      post "publish"
    end
  end

  resources :user_actions, :only=>[:create,:index,:update]

  mount Ckeditor::Engine => '/ckeditor'
  #mount JasmineRails::Engine => "/specs" unless Rails.env.production? || Rails.env.staging?

  post "zencoder-callback" => "zencoder#create", :as => "zencoder_callback"
  root :to => 'welcome#index'

  get 'video_credentials' => "video_upload_credentials#new"

end

app/models/view_item.rb
class ViewItem < ActiveRecord::Base
  has_ancestry :orphan_strategy => :destroy
  has_position_for_ancestry
  has_one :project
  
  # parent_id shuld go out
  # ancestry should also go out
  mass_assignment_sanitizer = :logger
	attr_accessible :id, :html, :position, :item_type, :sub_type, :title, :file, :image, :parent_id,:vimeo_id,:youtube_id,:soundcloud_id, :video_file, :video_file_type, :show_link, :thumb_url
  
  validates_presence_of :item_type
  
  def self.type_grammar
    @@grammar ||= {
      'template_1' => {
        'video_list' => {:position=>0},
        'audio_list' => {:position=>1},
        'attachments_list' => {:position=>2},
        'dropzone_list' => {:position=>3},
      },
      'root'=>{},
    }
  end
  
  def as_json(options = {})
    attributes = ViewItem.attr_accessible[:default].as_json
    attributes = attributes + [:ancestry,:image_url,:thumbnail_url,:thumbnail_hover_url,:file_url,:file_ext]
    options[:only] = attributes 
    h = super(options)
    h[:image_url]             = image.remote_url if image_uid?
    h[:thumbnail_url]         = thumbnail.remote_url if thumbnail_uid?
    h[:thumbnail_hover_url]   = thumbnail_hover.remote_url  if thumbnail_hover_uid?
    
    if sub_type == 'upload'
      h[:video_url] = self.video_file.url
    end

    if file_uid?
      opts = {:query => {"response-content-disposition" => "attachment"}, :expires => Time.now + 120.minutes}
      h[:file_url]              = file.remote_url(opts)
      extname = File.extname(file.remote_url)
      h[:file_ext]              = extname[1..-1]
    end
    h
  end  
end

app/controllers/view_items_controller.rb
class ViewItemsController < ApplicationController
  
  # TODO Async file upload fails unless ....
  skip_before_filter :verify_authenticity_token, :only => [:update, :create]

  
  layout false
  before_filter :authenticate_user!
  before_filter :load_parent, :only=>[:create,:update]
  before_filter :set_klass

  respond_to :json

  def upload
    @view_item = ViewItem.find(params[:id])
    @view_item.video_file = params[:view_item][:video_file]

    if @view_item.save
      respond_with @view_item do |format|
        format.json { render :json => @view_item, :status => 200 }
      end
    else
      respond_with @view_item do |format|
        format.json { render :json => @view_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show
    @view_item = ViewItem.find(params[:id])
    respond_with @view_item
  end
  
  def destroy    
    @view_item = ViewItem.find(params[:id])
    #current_user.projects.find @view_item.root.project.id
    @view_item.destroy
    respond_with :nothing, location:''
  end
  
  def create
    #@klass.sanitize_for_mass_assignment(params[:view_item])
    @view_item = @klass.new(params[:view_item])
    @view_item.parent_id = @parent_view_item.id
    if @view_item.save
      respond_with @view_item do |format|
        format.json { render :json => @view_item, :status => 200 }
      end
    else
      respond_with @view_item do |format|
        format.json { render :json => @view_item.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    #@klass.sanitize_for_mass_assignment(params[:view_item])
    @view_item = @klass.find(params[:id])
    @view_item.update_attributes params[:view_item]
    @view_item.parent = @parent_view_item
    
    if @view_item.save
      respond_with @view_item do |format|
        format.json { render :json => @view_item, :status => 200 }
      end
    else
      respond_with @view_item do |format|
        format.json { render :json => @view_item.errors, :status => :unprocessable_entity }
      end
    end
  end

private
  
  def load_parent
    params[:view_item].delete(:ancestry) if params[:view_item][:ancestry].present?
    @parent_view_item = ViewItem.find params[:view_item_id]
  end
  
  def set_klass
    # @klass
    class_name = params[:view_item].present? ? params[:view_item][:item_type] || 'view-item' : 'view-item'
    class_name = class_name.gsub('-','_').camelize
    begin
      @klass = Module.const_get(class_name)
      @klass = ViewItem unless @klass.is_a?(Class)
    rescue NameError
      @klass = ViewItem
    end
  end
end

app/helpers/view_items_helper.rb
module ViewItemsHelper
end

app/views/view_items/_form.html.haml
= form_for(@view_item) do |f|
  - if @view_item.errors.any?
    #error_explanation
      %h2
        = pluralize(@view_item.errors.count, "error")
        prohibited this view_item from being saved:
      %ul
        - @view_item.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :ancestry
    %br/
    = f.text_field :ancestry
  .field
    = f.label :position
    %br/
    = f.number_field :position
  .field
    = f.label :item_type
    %br/
    = f.text_field :item_type
  .field
    = f.label :html
    %br/
    = f.text_area :html
  .actions
    = f.submit

app/views/view_items/edit.html.haml
%h1 Editing view_item
= render 'form'
= link_to 'Show', @view_item
|
\#{link_to 'Back', view_items_path}


:javascript
	

app/views/view_items/editor_development.html.haml
.template
  .video_list
    %h1.video_title
      Lorem ipsum dolor
    .video_player_container
      = render :partial=>'z_test/video'
    .videos
      .video
      .video
      .video
  .audio_list
    %h2.title
      Soundtracks
    %p.note
      Click on track to play.
    %ul.tracks
      %li
        In hac habitasse platea dictumst.
      %li
        Aliquam erat volutpat.
      %li
        Vestibulum ante ipsum primis in faucibus.                  
    .audio_player
      = render :partial=>'z_test/audio'
  .attachments_list
    %h2.title
      Attachments
    .attachments
      %a.attachment{:href=>'#'}
        .icon.doc
        .name
          Read me
      %a.attachment{:href=>'#'}
        .icon.jpg
        .name
          Cover Image
      %a.attachment{:href=>'#'}
        .icon.mov
        .name
          Download trailer
      %a.attachment{:href=>'#'}
        .icon.zip
        .name
          Download all
  .panel
    .text
      %h2 Lorem ipsum dolor sit amet, consectetur adipiscing elit
      %p
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget libero eu dui vehicula pellentesque. Aenean rhoncus feugiat sapien, id mattis lacus posuere sit amet. Curabitur condimentum scelerisque tellus, eu gravida arcu venenatis eu. Aenean nec enim dolor. Fusce eu metus enim. Vestibulum dictum adipiscing massa sit amet tempus. Mauris egestas pretium dui, ac dapibus felis viverra eu. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec et neque quis lorem mollis varius et at dolor. Donec enim nulla, dictum elementum congue a, tincidunt nec neque.
      %h3
        Pellentesque habitant morbi tristique senectus
      %p
        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris venenatis metus at arcu semper scelerisque. Pellentesque mollis hendrerit diam, vel cursus tortor luctus eu. Donec orci tortor, accumsan et fringilla non, mattis in turpis. Nam condimentum, nunc eget suscipit vulputate, ipsum nibh condimentum elit, quis posuere sem ipsum eget sem. Proin laoreet dignissim lacus, vel hendrerit massa commodo vel. Aenean laoreet dui a massa cursus in blandit sem vulputate.
      %h4
        In hac habitasse platea dictumst
      %p
        In hac habitasse platea dictumst. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris pretium ullamcorper ligula id eleifend. Sed mattis, elit quis placerat varius, metus diam sollicitudin purus, et adipiscing nunc erat sit amet purus. Nunc a magna non ante varius pharetra. Praesent elementum lorem ut purus porttitor aliquam. Aenean risus felis, ornare vel eleifend nec, varius rhoncus tortor. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam in viverra sapien.
      %h5
        Phasellus velit quam, porta ut elementum a, semper in leo
      %p
        Phasellus velit quam, porta ut elementum a, semper in leo. Sed arcu mi, ultrices nec gravida non, consequat nec dui. Donec lacus massa, venenatis eget accumsan id, mattis at leo. Proin eu mauris ligula, quis eleifend lacus. Pellentesque eget erat velit. Pellentesque ultrices, odio nec egestas aliquam, dui enim egestas orci, non feugiat risus lorem vel nisi. Nulla mollis laoreet lectus eu molestie. Sed in libero nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque accumsan porta gravida.

app/views/view_items/index.html.haml
#main-editor
  Loading...

%script{ :type => "text/template", :id => "editor-template" }
  %h1 Listing view_items
  %table
    %tr
      %th Ancestry
      %th Position
      %th Item type
      %th Html
      %th
      %th
      %th
    - @view_items.each do |view_item|
      %tr
        %td= view_item.ancestry
        %td= view_item.position
        %td= view_item.item_type
        %td= view_item.html
        %td= link_to 'Show', view_item
        %td= link_to 'Edit', edit_view_item_path(view_item)
        %td= link_to 'Destroy', view_item, confirm: 'Are you sure?', method: :delete
  %br/
  = link_to 'New View item', new_view_item_path

%script{ :type => "text/template", :id => "viewItem-template" }
  View Item Template

app/views/view_items/new.html.haml
%h1 New view_item
= render 'form'
= link_to 'Back', view_items_path