config/routes.rb
Vsr::Application.routes.draw do
  devise_for :user, :path=>'user', :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
  end

  match "editor_sample" => "projects#editor_sample"
  match "presentation/:id" => "projects#preview", :as => :presentation

  resources :admin_rights, only: [:destroy]
  resources :user_activations, :only => [:edit,:update, :index, :create, :destroy]  
  resources :contacts, :only => [:create, :destroy, :index, :update]
  resources :view_items do
    resources :view_items, :only=>[:create,:update,:destroy, :show]
  end
  resources :invitations

  resources :contact_groups do
    resources :contacts, :only => [:create, :update, :destroy, :show, :index]
  end

  resources :projects do
    resources :viewers, :only=>[:create,:destroy,:index] do
      resources :invitations
    end

    resources :user_actions, :only=>[:create,:index,:update]

    collection do
      get :dashboard
    end

    member do
      get 'edit_presentation'
      get 'preview'
      post "publish"
    end
  end

  resources :user_actions, :only=>[:create,:index,:update]

  mount Ckeditor::Engine => '/ckeditor'
  #mount JasmineRails::Engine => "/specs" unless Rails.env.production? || Rails.env.staging?

  post "zencoder-callback" => "zencoder#create", :as => "zencoder_callback"
  root :to => 'welcome#index'

  get 'video_credentials' => "video_upload_credentials#new"

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :viewer, :class_name=>'User',:foreign_key=>'user_id'
  belongs_to :creator, :class_name=>'User',:foreign_key=>'creator_id'
  belongs_to :project
  
  validates_presence_of :viewer
  validates_presence_of :creator
  validates_presence_of :project
  
  after_create :send_invitation
  
  def self.create_invitation project, creator, viewer, options
    invitation = Invitation.new(options)
    invitation.creator = creator
    invitation.project = project
    invitation.viewer  = viewer
    invitation.save
  end

  def update_message message
    self.update_attribute :message, message
    send_invitation
  end

private
  def send_invitation
    self.viewer.update_attribute(:after_activation_path, "/invitations/#{self.id}") unless viewer.activated?
    InvitationMailer.delay.invitation_mail(self)
  end
  
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_project_and_viewer, :only => [:create]
  
  respond_to :json

  def create
    @invitation = Invitation.new(params[:invitation])
    @invitation.creator = current_user
    @invitation.project = @project
    @invitation.viewer  = @viewer
    @invitation.save
    respond_with @invitation, :url=>nil, :location => nil
  end

  def show
    @invitation = Invitation.find(params[:id])
    redirect_to presentation_path(@invitation.project)
  end

private
  def load_project_and_viewer
    @project = current_user.projects.find(params[:project_id])
    @viewer  = @project.viewers.find(params[:viewer_id]).connected_user
  end
  
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.haml
= form_for(@invitation) do |f|
  - if @invitation.errors.any?
    #error_explanation
      %h2
        = pluralize(@invitation.errors.count, "error")
        prohibited this invitation from being saved:
      %ul
        - @invitation.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :message
    %br/
    = f.text_field :message
  .field
    = f.label :token
    %br/
    = f.text_field :token
  .field
    = f.label :viewed_at
    %br/
    = f.datetime_select :viewed_at
  .field
    = f.label :creator_id
    %br/
    = f.number_field :creator_id
  .field
    = f.label :project_id
    %br/
    = f.number_field :project_id
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .actions
    = f.submit

app/views/invitations/edit.html.haml
%h1 Editing invitation
= render 'form'
= link_to 'Show', @invitation
|
\#{link_to 'Back', invitations_path}

app/views/invitations/index.html.haml
%h1 Listing invitations
%table
  %tr
    %th Message
    %th Token
    %th Viewed at
    %th Creator
    %th Project
    %th User
    %th
    %th
    %th
  - @invitations.each do |invitation|
    %tr
      %td= invitation.message
      %td= invitation.token
      %td= invitation.viewed_at
      %td= invitation.creator_id
      %td= invitation.project_id
      %td= invitation.user_id
      %td= link_to 'Show', invitation
      %td= link_to 'Edit', edit_invitation_path(invitation)
      %td= link_to 'Destroy', invitation, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Invitation', new_invitation_path

app/views/invitations/new.html.haml
%h1 New invitation
= render 'form'
= link_to 'Back', invitations_path

app/views/invitations/show.html.haml
%h1 
  Project title:
  = @invitation.project.title
%p Invitation to new presentation

%p= @invitation.project.description

- if @invitation.message.present?
  %p
    %b Message
    %br
    = @invitation.message

= button_to 'Continue to Presentation', presentation_path(@invitation.project), :method => :get