config/routes.rb
Vsr::Application.routes.draw do
  devise_for :user, :path=>'user', :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
  end

  match "editor_sample" => "projects#editor_sample"
  match "presentation/:id" => "projects#preview", :as => :presentation

  resources :admin_rights, only: [:destroy]
  resources :user_activations, :only => [:edit,:update, :index, :create, :destroy]  
  resources :contacts, :only => [:create, :destroy, :index, :update]
  resources :view_items do
    resources :view_items, :only=>[:create,:update,:destroy, :show]
  end
  resources :invitations

  resources :contact_groups do
    resources :contacts, :only => [:create, :update, :destroy, :show, :index]
  end

  resources :projects do
    resources :viewers, :only=>[:create,:destroy,:index] do
      resources :invitations
    end

    resources :user_actions, :only=>[:create,:index,:update]

    collection do
      get :dashboard
    end

    member do
      get 'edit_presentation'
      get 'preview'
      post "publish"
    end
  end

  resources :user_actions, :only=>[:create,:index,:update]

  mount Ckeditor::Engine => '/ckeditor'
  #mount JasmineRails::Engine => "/specs" unless Rails.env.production? || Rails.env.staging?

  post "zencoder-callback" => "zencoder#create", :as => "zencoder_callback"
  root :to => 'welcome#index'

  get 'video_credentials' => "video_upload_credentials#new"

end

app/controllers/user_activations_controller.rb
class UserActivationsController < ApplicationController  
  before_filter :authenticate_user!, :only=> [:update, :index, :destroy]
  before_filter :super_user, :only => [:index, :create, :destroy]

  def index
    @admins = User.where(super_user: true) - [current_user]
    @active_users = User.where(super_user: false).where(activated: true)
    @inactive_users = User.where(super_user: false).where(activated: false)
  end

  def create
    if params[:email].present?
      existing_user = User.find_by_email params[:email]  
      if existing_user
        existing_user.update_attribute :super_user, true
      else
        user = User.new_with_activation(email: params[:email])
        user.super_user = true
        if user.save
          InvitationMailer.new_admin_activate(user).deliver
        end
      end
    end
    
    redirect_to :back   
  end

  def destroy
    if params[:id].present?
      user = User.find params[:id]
      user.destroy
    end
    redirect_to :back
  end
  
  def edit
    @user = User.where(activation_token:params[:id]).first

    if @user
      # already activated
      if @user.activated?
        if @user.after_activation_path
          redirect_to @user.after_activation_path
        else
          redirect_to root_path
        end
      else
        # show password change
        if current_user and current_user != @user
          sign_out current_user
          sign_in @user
        else
          sign_in @user
        end
      end
    else
      notice[:warn] = "This link has expired."
    end
  end
  
  def update
    @user = current_user
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    @user.activated = true
    if @user.save
      sign_out current_user
      sign_in @user

      if @user.after_activation_path
        redirect_to @user.after_activation_path
      else
        redirect_to root_path
      end
    else
      render :edit, :status=>:unprocessable_entity
    end
  end

private
  def super_user
    current_user.super_user?
  end
end

app/views/user_activations/edit.html.erb
<h2>Activate your account</h2>

<%= form_for(@user, :url => user_activation_path(@user.activation_token), :html => { :method => :put }) do |f| %>

  <div><%= f.label :password, "Password" %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation, "Confirm password" %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Create Your Password" %></div>
<% end %>

app/views/user_activations/index.html.haml
%h3 Users

.new-admin
  %h3 add new admin user
  = form_tag user_activations_path do
    = label_tag :email, "Enter user's email"
    %br
    = text_field_tag :email
    = submit_tag 'Add'

.users-list
  %h4 Admin Users
  %ul
    - @admins.each do |admin|
      %li
        = admin.email
        = link_to 'remove admin rights', admin_right_path(admin.id, :confirm => 'Are you sure ?'), :method => :delete
        |
        = link_to 'remove', user_activation_path(admin.id, :confirm => 'Are you sure ?'), :method => :delete

.users-list
  %h4 Active Users
  %ul
    - @active_users.each do |user|
      %li
        = user.email
        = link_to 'remove', user_activation_path(user.id, :confirm => "Are you sure ?"), :method => :delete

.users-list
  %h4 Inactive Users
  %ul
    - @inactive_users.each do |user|
      %li
        = user.email
        = link_to 'remove', user_activation_path(user.id, :confirm => "Are you sure ?"), :method => :delete

.clear

.actions
  = link_to "Back", root_path