config/routes.rb
Vsr::Application.routes.draw do
  devise_for :user, :path=>'user', :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
  end

  match "editor_sample" => "projects#editor_sample"
  match "presentation/:id" => "projects#preview", :as => :presentation

  resources :admin_rights, only: [:destroy]
  resources :user_activations, :only => [:edit,:update, :index, :create, :destroy]  
  resources :contacts, :only => [:create, :destroy, :index, :update]
  resources :view_items do
    resources :view_items, :only=>[:create,:update,:destroy, :show]
  end
  resources :invitations

  resources :contact_groups do
    resources :contacts, :only => [:create, :update, :destroy, :show, :index]
  end

  resources :projects do
    resources :viewers, :only=>[:create,:destroy,:index] do
      resources :invitations
    end

    resources :user_actions, :only=>[:create,:index,:update]

    collection do
      get :dashboard
    end

    member do
      get 'edit_presentation'
      get 'preview'
      post "publish"
    end
  end

  resources :user_actions, :only=>[:create,:index,:update]

  mount Ckeditor::Engine => '/ckeditor'
  #mount JasmineRails::Engine => "/specs" unless Rails.env.production? || Rails.env.staging?

  post "zencoder-callback" => "zencoder#create", :as => "zencoder_callback"
  root :to => 'welcome#index'

  get 'video_credentials' => "video_upload_credentials#new"

end

app/views/layouts/application.html.haml
<!doctype html>
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
=raw '<!--[if gt IE 8]>'
%html.no-js{:lang => "en"}
  =raw '<![endif]-->'
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %title VSR
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    -#= stylesheet_link_tag 'print.css', :media => 'print'
    /[if IE]
      -#= stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = csrf_meta_tags
    :javascript
      viewingMode = '#{@mode}';
      var CKEDITOR_BASEPATH = '/ckeditor/';
      // var CKEDITOR_BASEPATH = '/assets/ckeditor/';

    - if Rails.env.development?
      = javascript_include_tag "development"
    - else
      = javascript_include_tag "application"

    %script{:src => "/ckeditor/ckeditor.js"}
    %script{:src => "/ckeditor/adapters/jquery.js"}
  %body#container.admin
    /[if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
    #background-panel
    #foreground-panel
    #main-container
      #header-container
        - if user_signed_in?
          %ul.hmenu        
            = render 'devise/menu/registration_items'
            = render 'devise/menu/login_items'
  
          %header.clearfix
            %h1#title
      #main.wrapper.clearfix
        #main-panel
          - if user_signed_in?
            - if notice
              %p.notice= notice
            - if alert
              %p.alert= alert
          = yield
      
    #footer-container
      %footer
        %p Copyright 2012, Village Screening Room

      / #main
    / #main-container

    /
    :javascript
      var _gaq=[['_setAccount','UA-47924149-1'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));
    

app/views/layouts/editor.html.haml
<!doctype html>
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
=raw '<!--[if gt IE 8]>'
%html.no-js{:lang => "en"}
  =raw '<![endif]-->'
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %title VSR
    %link{:href => "http://vjs.zencdn.net/c/video-js.css", :rel => "stylesheet"}
    %script{:src => "http://vjs.zencdn.net/c/video.js"}
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    %link{:href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/themes/ui-lightness/jquery-ui.css", :rel => "stylesheet", :type => "text/css"}

    -#= stylesheet_link_tag 'print.css', :media => 'print'
    /[if IE]
      -#= stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = csrf_meta_tags

    :javascript
      viewingMode = '#{@mode}';

    - if Rails.env.development?
      = javascript_include_tag "development"
    - else
      = javascript_include_tag "application"

    %script{:src => "/ckeditor/ckeditor.js"}
    %script{:src => "/ckeditor/adapters/jquery.js"}

    %link{:rel => 'stylesheet', :href => '/jquery-file-upload/css/jquery.fileupload-ui.css'}
    %script{:src => "/jquery-file-upload/js/vendor/jquery.ui.widget.js"}
    %script{:src => "/jquery-file-upload/js/jquery.iframe-transport.js"}
    %script{:src => "/jquery-file-upload/js/jquery.fileupload.js"}
    %script{:src => "/jquery-file-upload/js/jquery.fileupload-fp.js"}
    %script{:src => "/jquery-file-upload/js/jquery.fileupload-ui.js"}
    %script{:src => "/jquery-file-upload/js/locale.js"}
      
  %body#container.editor.screening_body{:data=>{'view-items'=>@view_items.to_json,'project-id'=>@project.id,'root-id'=>@project.draft_id}}
    %input{:type=>'hidden', :value=>ENV["AWS_DIRECTORY"], :id=>'aws_directory'}
    /[if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
    #foreground-panel
    #editor-header
      .left
        %span.project_title= @project.title
        = link_to 'back', projects_path(:anchor => project_path(@project)[1..-1]), :class=>'back'
      .right
        = link_to 'publish', '#', :class => 'publish button'
        = link_to 'preview', presentation_path(@project), :class => 'save button'
      #editing-toolbar
    #trash
    #main-container.screening
      #main-panel
          
      / #main
    / #main-container
    :javascript
      var _gaq=[['_setAccount','UA-47924149-1'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/layouts/preview.html.haml
<!doctype html>
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
=raw '<!--[if gt IE 8]>'
%html.no-js{:lang => "en"}
  =raw '<![endif]-->'
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %title VSR
    %link{:href => "http://vjs.zencdn.net/c/video-js.css", :rel => "stylesheet"}
    %script{:src => "http://vjs.zencdn.net/c/video.js"}
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    -#= stylesheet_link_tag 'print.css', :media => 'print'
    -#/[if IE]
      -#= stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = csrf_meta_tags
    
    :javascript
      viewingMode = '#{@mode}';

    - if Rails.env.development?
      = javascript_include_tag "development"
    - else
      = javascript_include_tag "application"

  %body#container.preview.screening_body{:data=>{'view-items'=>@view_items.to_json,'project-id'=>@project.id,'root-id'=>@project.view_item_id}}
    -#/[if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
    #foreground-panel
    #editor-header
      - if current_user == @project.creator
        .left
          %span.project_title= @project.title
          = link_to 'Other projects', projects_path(:anchor => project_path(@project)[1..-1]), :class=>'back'
        .right
          = link_to 'publish', '#', :class => 'publish button'
          = link_to 'back to edit mode', edit_presentation_project_path(:anchor => edit_presentation_project_path(@project)[1..-1]), :class=>'button back_to_edit'        
      - else
        .left
          %span.project_title= @project.title
          = link_to 'Other projects', root_path, :class=>'back'
        #editing-toolbar
    #main-container.screening.preview
      #main-panel
          
      / #main
    / #main-container
    :javascript
      var _gaq=[['_setAccount','UA-47924149-1'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));